import 'package:flutter/material.dart';

import '../../../../design_system/colors.dart';
import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../../celestial/domain/celestial_kind.dart';
import '../domain/tracker_models.dart';

class TrackerShareCard extends StatelessWidget {
  const TrackerShareCard({super.key, required this.result});

  final TrackerResult result;

  String _fmt(double v, int digits) => v.toStringAsFixed(digits);

  String _date() {
    final d = result.timestamp.toLocal();
    final months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${d.day} ${months[d.month - 1]} ${d.year}';
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: AppColors.bgDeepest,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.accentPrimary.withValues(alpha: 0.08),
            Colors.transparent,
          ],
        ),
        border: Border.all(color: AppColors.borderSubtle, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'UNDERDECK · TRACKER',
            style: AppTypography.mono.copyWith(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 2,
              color: AppColors.accentPrimary,
            ),
          ),
          const SizedBox(height: 3),
          Text(_date(), style: AppTypography.caption),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.md),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(result.kind.emoji, style: const TextStyle(fontSize: 22)),
              const SizedBox(width: AppSpacing.sm),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(result.displayName, style: AppTypography.headline),
                    const SizedBox(height: 2),
                    Text(
                      'MPC ${result.mpcID}',
                      style: AppTypography.mono.copyWith(
                        fontSize: 11,
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          _Row(
            label: 'Sector',
            value: '${result.sector}',
            valueSize: 22,
            valueColor: AppColors.accentPrimary,
          ),
          _Row(
            label: 'Distance',
            value: '${_fmt(result.slRounded, 3)} SL',
            valueColor: AppColors.accentSecondary,
          ),
          _Row(label: 'AU', value: _fmt(result.distanceAU, 3)),
          _Row(label: 'X (AU)', value: _fmt(result.xAU, 3)),
          _Row(label: 'Y (AU)', value: _fmt(result.yAU, 3)),
          _Row(label: 'Z (AU)', value: _fmt(result.zAU, 3)),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(Icons.wifi_tethering, size: 9, color: AppColors.textDim),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · ESSI real-time tracking',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: AppColors.textDim,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({
    required this.label,
    required this.value,
    this.valueSize = 14,
    this.valueColor = AppColors.textPrimary,
  });
  final String label;
  final String value;
  final double valueSize;
  final Color valueColor;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        children: [
          Expanded(child: Text(label, style: AppTypography.caption)),
          Text(
            value,
            style: AppTypography.mono.copyWith(
              fontSize: valueSize,
              fontWeight: FontWeight.w600,
              color: valueColor,
            ),
          ),
        ],
      ),
    );
  }
}
