import 'package:flutter/material.dart';

import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../domain/map_enums.dart';
import '../domain/map_models.dart';
import '../domain/map_theme.dart';

/// Branded, fixed-width share card for a single map [MapZone] (AUDIT-V2 §6.8).
///
/// Part of the JobShareCard/FishingShareCard family — same header/divider/row
/// layout so exported PNGs read as one set — but themed to the map's [MapTheme]
/// (background, label, accent, font) rather than the app palette. Rendered
/// off-screen by [ShareCardCapture]; not interactive.
///
/// Contains game data only (map title, zone name, schema-driven field values):
/// no personal note text, no PII.
class MapZoneShareCard extends StatelessWidget {
  const MapZoneShareCard({
    super.key,
    required this.mapTitle,
    required this.zone,
    required this.fieldsSchema,
    required this.theme,
  });

  final String mapTitle;
  final MapZone zone;
  final List<ZoneFieldSpec> fieldsSchema;
  final MapTheme theme;

  /// The first few schema fields with a shareable scalar/list value. Skips
  /// long-form / link fields (too verbose for a card) and empty values.
  List<(String, String)> _rows() {
    final out = <(String, String)>[];
    for (final spec in fieldsSchema) {
      if (out.length >= 5) break;
      if (spec.type == ZoneFieldType.longText ||
          spec.type == ZoneFieldType.link) {
        continue;
      }
      final value = _format(spec, zone.fields[spec.key]);
      if (value == null) continue;
      out.add((spec.label, value));
    }
    return out;
  }

  static String? _format(ZoneFieldSpec spec, Object? raw) {
    if (raw == null) return null;
    if (raw is List) {
      final items = [
        for (final e in raw) ?_scalar(e),
      ];
      return items.isEmpty ? null : items.join(', ');
    }
    final s = _scalar(raw);
    if (s == null) return null;
    if (spec.type == ZoneFieldType.number && spec.unit != null) {
      return '$s ${spec.unit}';
    }
    return s;
  }

  static String? _scalar(Object? raw) {
    if (raw is String) return raw.trim().isEmpty ? null : raw.trim();
    if (raw is num || raw is bool) return raw.toString();
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final rows = _rows();
    final divider = theme.zoneStroke.withValues(alpha: 0.4);
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: theme.background,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            theme.accent.withValues(alpha: 0.10),
            Colors.transparent,
          ],
        ),
        border: Border.all(
          color: theme.zoneStroke.withValues(alpha: 0.5),
          width: 1,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'UNDERDECK · MAP',
            style: AppTypography.mono.copyWith(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 2,
              color: theme.accent,
            ),
          ),
          const SizedBox(height: 3),
          Text(
            mapTitle,
            style: AppTypography.caption.copyWith(
              color: theme.label.withValues(alpha: 0.7),
            ),
          ),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: divider),
          const SizedBox(height: AppSpacing.md),
          Text(
            zone.name,
            style: AppTypography.headline.copyWith(
              fontFamily: theme.fontFamily,
              color: theme.label,
            ),
          ),
          if (rows.isNotEmpty) const SizedBox(height: AppSpacing.md),
          for (final r in rows) _Row(label: r.$1, value: r.$2, theme: theme),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: divider),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(Icons.map_outlined,
                  size: 9, color: theme.label.withValues(alpha: 0.5)),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · Interactive maps',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: theme.label.withValues(alpha: 0.5),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({required this.label, required this.value, required this.theme});

  final String label;
  final String value;
  final MapTheme theme;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 110,
            child: Text(
              label,
              style: AppTypography.caption.copyWith(
                color: theme.label.withValues(alpha: 0.55),
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: AppTypography.mono.copyWith(
                fontSize: 13,
                fontWeight: FontWeight.w600,
                color: theme.label,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
