import 'package:flutter/material.dart';

import '../../../../design_system/colors.dart';
import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../domain/job.dart';
import '../domain/job_taxonomies.dart';

/// Branded, fixed-width share card for a single [Job].
///
/// Mirrors the layout of [TrackerShareCard] so the exported PNGs read as one
/// family. Rendered off-screen by [ShareCardCapture]; not interactive.
class JobShareCard extends StatelessWidget {
  const JobShareCard({super.key, required this.job});

  final Job job;

  @override
  Widget build(BuildContext context) {
    final ally = JobTaxonomies.lookup(job.factionRep);
    final rival = JobTaxonomies.lookup(job.factionRival);
    final rewardLabel = JobTaxonomies.rewardLabel(job.reward);
    final bonus = job.bonus == 0
        ? 'amount unknown'
        : (job.bonus > 0 ? '+${job.bonus}' : '${job.bonus}');
    final skill = job.requiredSkill == null
        ? '—'
        : '${job.requiredSkill}${job.requiredSkillAmt > 0 ? ' ≥${job.requiredSkillAmt}' : ''}';
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: AppColors.bgDeepest,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.accentPrimary.withValues(alpha: 0.08),
            Colors.transparent,
          ],
        ),
        border: Border.all(color: AppColors.borderSubtle, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'UNDERDECK · JOB',
            style: AppTypography.mono.copyWith(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 2,
              color: AppColors.accentPrimary,
            ),
          ),
          const SizedBox(height: 3),
          Text('Contract #${job.id}', style: AppTypography.caption),
          const SizedBox(height: AppSpacing.md),
          Container(
              height: 1,
              color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.md),
          Text(
            job.typeRaw.toUpperCase(),
            style: AppTypography.headline,
          ),
          const SizedBox(height: AppSpacing.md),
          _Row(
            label: 'Allied faction',
            value: ally?.label ?? '—',
            valueColor: ally?.tint ?? AppColors.textPrimary,
          ),
          if (rival != null)
            _Row(
              label: 'Rival faction',
              value: rival.label,
              valueColor: rival.tint,
            ),
          _Row(
            label: 'Reward',
            value: '$rewardLabel · $bonus',
            valueColor: JobTaxonomies.rewardTint(job.reward),
          ),
          _Row(label: 'Required skill', value: skill),
          _Row(
            label: 'Risk',
            value: '${job.risk}',
            valueColor: AppColors.accentWarn,
          ),
          _Row(label: 'Pickup', value: job.pickup.coordsLabel),
          _Row(label: 'Dropoff', value: job.dropoff.coordsLabel),
          const SizedBox(height: AppSpacing.md),
          Container(
              height: 1,
              color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(Icons.work_outline, size: 9, color: AppColors.textDim),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · Job board',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: AppColors.textDim,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({
    required this.label,
    required this.value,
    this.valueColor = AppColors.textPrimary,
  });
  final String label;
  final String value;
  final Color valueColor;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 110,
            child: Text(label, style: AppTypography.caption),
          ),
          Expanded(
            child: Text(
              value,
              style: AppTypography.mono.copyWith(
                fontSize: 13,
                fontWeight: FontWeight.w600,
                color: valueColor,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
