import 'package:flutter/material.dart';

import '../../../../design_system/colors.dart';
import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../domain/fishing_models.dart';

/// Branded, fixed-width share card for a single fishing [FishingZone].
///
/// Mirrors the layout of the tracker/job share cards so exported PNGs read as
/// one family. Rendered off-screen by [ShareCardCapture]; not interactive.
class FishingShareCard extends StatelessWidget {
  const FishingShareCard({
    super.key,
    required this.zone,
    required this.roomLabel,
  });

  final FishingZone zone;
  final String roomLabel;

  @override
  Widget build(BuildContext context) {
    final depth = FishingDepth.fromName(zone.depth);
    final tint = depth?.color ?? AppColors.accentPrimary;
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: AppColors.bgDeepest,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            tint.withValues(alpha: 0.08),
            Colors.transparent,
          ],
        ),
        border: Border.all(color: AppColors.borderSubtle, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'UNDERDECK · FISHING',
            style: AppTypography.mono.copyWith(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 2,
              color: AppColors.accentPrimary,
            ),
          ),
          const SizedBox(height: 3),
          Text(roomLabel, style: AppTypography.caption),
          const SizedBox(height: AppSpacing.md),
          Container(
              height: 1,
              color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.md),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: tint.withValues(alpha: 0.55),
                  shape: BoxShape.circle,
                ),
              ),
              const SizedBox(width: AppSpacing.sm),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(zone.name, style: AppTypography.headline),
                    const SizedBox(height: 2),
                    Text(
                      'Zone ${zone.id}',
                      style: AppTypography.mono.copyWith(
                        fontSize: 11,
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          _Row(label: 'Room', value: roomLabel),
          _Row(
            label: 'Depth',
            value: zone.depth ?? 'n/a',
            valueColor: tint,
          ),
          _Row(label: 'Pole', value: zone.pole ?? 'n/a'),
          _Row(
            label: 'Access',
            value: zone.accessible ? 'Accessible' : 'No (Reef)',
            valueColor: zone.accessible
                ? AppColors.accentSuccess
                : AppColors.accentDanger,
          ),
          const SizedBox(height: AppSpacing.md),
          Container(
              height: 1,
              color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(Icons.set_meal, size: 9, color: AppColors.textDim),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · Fishing map',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: AppColors.textDim,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({
    required this.label,
    required this.value,
    this.valueColor = AppColors.textPrimary,
  });
  final String label;
  final String value;
  final Color valueColor;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 2),
      child: Row(
        children: [
          Expanded(child: Text(label, style: AppTypography.caption)),
          Text(
            value,
            style: AppTypography.mono.copyWith(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: valueColor,
            ),
          ),
        ],
      ),
    );
  }
}
