import 'package:flutter/material.dart';

import '../../../../design_system/colors.dart';
import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../views/wallet_lookup_view.dart';

class WalletShareCard extends StatelessWidget {
  const WalletShareCard({
    super.key,
    required this.query,
    required this.ownerHits,
    required this.walletHits,
  });

  final String query;
  final List<WalletEntry> ownerHits;
  final List<({String wallet, WalletEntry owner})> walletHits;

  static const _maxOwners = 6;
  static const _maxWallets = 8;

  @override
  Widget build(BuildContext context) {
    final ownerCap = ownerHits.take(_maxOwners).toList();
    final remaining = (_maxOwners - ownerCap.length).clamp(0, _maxOwners);
    final ownerIds = ownerHits.map((e) => e.id).toSet();
    final extraWallets = walletHits
        .where((h) => !ownerIds.contains(h.owner.id))
        .take(_maxWallets + remaining)
        .toList();
    final hidden =
        ownerHits.length + extraWallets.length - ownerCap.length - extraWallets.length;
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: AppColors.bgDeepest,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.accentPrimary.withValues(alpha: 0.08),
            Colors.transparent,
          ],
        ),
        border: Border.all(color: AppColors.borderSubtle, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'UNDERDECK · WALLET LOOKUP',
            style: AppTypography.mono.copyWith(
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 2,
              color: AppColors.accentPrimary,
            ),
          ),
          const SizedBox(height: 3),
          Text(
            'Query: "$query"',
            style: AppTypography.mono.copyWith(
              fontSize: 12,
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.md),
          if (ownerCap.isEmpty && extraWallets.isEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
              child: Text(
                'No matches.',
                style: AppTypography.caption,
              ),
            )
          else ...[
            for (final entry in ownerCap) ...[
              _OwnerBlock(entry: entry),
              const SizedBox(height: AppSpacing.sm),
            ],
            if (extraWallets.isNotEmpty) ...[
              const SizedBox(height: 4),
              Text(
                'WALLET MATCHES',
                style: AppTypography.mono.copyWith(
                  fontSize: 10,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.5,
                  color: AppColors.accentSecondary,
                ),
              ),
              const SizedBox(height: 4),
              for (final hit in extraWallets) ...[
                _WalletHitBlock(wallet: hit.wallet, owner: hit.owner),
                const SizedBox(height: 4),
              ],
            ],
            if (hidden > 0)
              Padding(
                padding: const EdgeInsets.only(top: AppSpacing.sm),
                child: Text(
                  '+$hidden more',
                  style: AppTypography.caption,
                ),
              ),
          ],
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(Icons.wallet, size: 9, color: AppColors.textDim),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · ESBE blockchain analysis',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: AppColors.textDim,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _OwnerBlock extends StatelessWidget {
  const _OwnerBlock({required this.entry});
  final WalletEntry entry;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(Icons.person, color: AppColors.accentPrimary, size: 14),
            const SizedBox(width: 6),
            Expanded(
              child: Text(entry.displayName, style: AppTypography.body),
            ),
            if (entry.discordUsername != null &&
                entry.discordUsername!.toLowerCase() !=
                    entry.displayName.toLowerCase())
              Text(
                '@${entry.discordUsername}',
                style: AppTypography.mono.copyWith(
                  fontSize: 11,
                  color: AppColors.accentSecondary,
                ),
              ),
          ],
        ),
        for (final wallet in entry.wallets)
          Padding(
            padding: const EdgeInsets.only(left: 20, top: 1),
            child: Text(
              wallet,
              style: AppTypography.mono.copyWith(
                fontSize: 10,
                color: AppColors.textPrimary,
              ),
            ),
          ),
      ],
    );
  }
}

class _WalletHitBlock extends StatelessWidget {
  const _WalletHitBlock({required this.wallet, required this.owner});
  final String wallet;
  final WalletEntry owner;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(Icons.wallet, color: AppColors.accentSecondary, size: 14),
            const SizedBox(width: 6),
            Expanded(
              child: Text(
                wallet,
                style: AppTypography.mono.copyWith(
                  fontSize: 11,
                  fontWeight: FontWeight.w600,
                  color: AppColors.textPrimary,
                ),
              ),
            ),
          ],
        ),
        Padding(
          padding: const EdgeInsets.only(left: 20),
          child: Text(
            'Registered to ${owner.displayName}',
            style: AppTypography.caption,
          ),
        ),
      ],
    );
  }
}
