import 'package:flutter/material.dart';

import '../../../../design_system/colors.dart';
import '../../../../design_system/spacing.dart';
import '../../../../design_system/typography.dart';
import '../domain/scan_models.dart';
import 'planet_result_row.dart';

class ScanShareCard extends StatelessWidget {
  const ScanShareCard({
    super.key,
    required this.mode,
    required this.date,
    required this.snapshots,
  });

  final ScanMode mode;
  final DateTime date;
  final List<PlanetPosition> snapshots;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        color: AppColors.bgDeepest,
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.accentPrimary.withValues(alpha: 0.08),
            Colors.transparent,
          ],
        ),
        border: Border.all(color: AppColors.borderSubtle, width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _Header(mode: mode, date: date),
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.md),
          for (var i = 0; i < snapshots.length; i++) ...[
            PlanetResultRow(
              row: PlanetRow(
                name: snapshots[i].name,
                emoji: snapshots[i].emoji,
                status: PlanetRowOk(snapshots[i]),
              ),
              staticGlyph: true,
            ),
            if (i < snapshots.length - 1)
              Container(
                height: 1,
                margin: const EdgeInsets.symmetric(vertical: 2),
                color: AppColors.borderSubtle.withValues(alpha: 0.25),
              ),
          ],
          const SizedBox(height: AppSpacing.md),
          Container(height: 1, color: AppColors.borderSubtle.withValues(alpha: 0.5)),
          const SizedBox(height: AppSpacing.sm),
          Row(
            children: [
              Icon(
                Icons.wifi_tethering,
                size: 9,
                color: AppColors.textDim,
              ),
              const SizedBox(width: 4),
              Text(
                'Generated by Underdeck · ESSI deep space monitoring',
                style: AppTypography.mono.copyWith(
                  fontSize: 9,
                  color: AppColors.textDim,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Header extends StatelessWidget {
  const _Header({required this.mode, required this.date});
  final ScanMode mode;
  final DateTime date;

  String _date() {
    final h = date.hour.toString().padLeft(2, '0');
    final m = date.minute.toString().padLeft(2, '0');
    final s = date.second.toString().padLeft(2, '0');
    final months = [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${date.day} ${months[date.month - 1]} ${date.year}, $h:$m:$s';
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'UNDERDECK · SYSTEM SCAN',
                style: AppTypography.mono.copyWith(
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 2,
                  color: AppColors.accentPrimary,
                ),
              ),
              const SizedBox(height: 3),
              Text(
                _date(),
                style: AppTypography.mono.copyWith(
                  fontSize: 12,
                  color: AppColors.textSecondary,
                ),
              ),
            ],
          ),
        ),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 3),
          decoration: BoxDecoration(
            border: Border.all(
              color: AppColors.accentPrimary.withValues(alpha: 0.6),
              width: 0.7,
            ),
            borderRadius: BorderRadius.circular(3),
          ),
          child: Text(
            mode.label.toUpperCase(),
            style: AppTypography.mono.copyWith(
              fontSize: 10,
              fontWeight: FontWeight.w700,
              letterSpacing: 1.5,
              color: AppColors.accentPrimary,
            ),
          ),
        ),
      ],
    );
  }
}
